"""baseline

Revision ID: 9b4da4ba26a7
Revises: 
Create Date: 2026-07-08 09:52:59.731378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b4da4ba26a7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('furnaces', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('furnaces', schema=None) as batch_op:
        batch_op.alter_column('is_active',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))

    # ### end Alembic commands ###
